/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reportes;

import Examenes.*;
import Examenes.*;
import Clases.MySQL;
import Clases.PantallaPrincipal;
import ModuloUsuario.ImgDoctor;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BayBay
 */
public class BuscarHemograma extends javax.swing.JInternalFrame {
private IniciarReporte jasper;
    /**
     * Creates new form EliminarAnimalP
     */
    public BuscarHemograma() {
        initComponents();
        ImgDoctor img = new ImgDoctor();
        jpImagen.add(img);
        jpImagen.repaint();
        cargarTabla();
        jlBuscarCasoClinico.setVisible(false);
        jasper = new IniciarReporte();
    }

    private void cargarTabla(){
        String[] columNames = {"Protocolo Lab","Caso Clinico","DNI del Duenio","Apellido","Nombre","Nombre Del Animal"};
        String colName[] = {"protocolo_lab","caso_clinico","dni_duenio","apellido","nombre","animal_pequenios.nombre"};
        //nombre de columnas, tabla, instruccion sql
        dtCasoClinico = casoClinico.GetTabla(colName, "consulta,duenio,animal_pequenios,doctor,hemograma", "SELECT * FROM `consulta`,`duenio`,`animal_pequenios`,`doctor`,`hemograma` WHERE (`consulta`.`cod_animal` =`animal_pequenios`.`cod_animal`) AND (`consulta`.`dni_doctor` =`doctor`.`dni_doctor`) AND (`animal_pequenios`.`dni_duenio` =`duenio`.`dni_duenio`)AND (`consulta`.`caso_clinico` = `hemograma`.`caso_clinico`)");
        // se colocan los datos en la tabla
        DefaultTableModel datos = new DefaultTableModel(dtCasoClinico, columNames);
        jtCasoClinico.setModel(datos);
        // se colocan los datos en la tabla
        int a = jtCasoClinico.getRowCount();
        //depurador de jtDuenio de item null
        int i=0;
        a--;
        while(a>=i){
            if(jtCasoClinico.getValueAt(i,1)==null){
                ((DefaultTableModel)jtCasoClinico.getModel()).removeRow(i);
                a--;
                i--;
            }
            i++;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jtfBuscar = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jrbProtocoloLab = new javax.swing.JRadioButton();
        jrbDni = new javax.swing.JRadioButton();
        jrbNombreAnimal = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jbElegir = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jpImagen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCasoClinico = new javax.swing.JTable();
        jlBuscarCasoClinico = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Buscar Analisis de Laboratorio de Hemograma");
        setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Analisis Por:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbProtocoloLab);
        jrbProtocoloLab.setSelected(true);
        jrbProtocoloLab.setText("Por Protocolo Laboratorio");

        buttonGroup1.add(jrbDni);
        jrbDni.setText("Por DNI Dueño");

        buttonGroup1.add(jrbNombreAnimal);
        jrbNombreAnimal.setText("Por Nombre Animal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbProtocoloLab)
                    .addComponent(jrbDni)
                    .addComponent(jrbNombreAnimal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrbProtocoloLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbDni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbNombreAnimal))
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jbElegir.setText("Elegir");
        jbElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbElegirActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jpImagen.setPreferredSize(new java.awt.Dimension(128, 128));

        javax.swing.GroupLayout jpImagenLayout = new javax.swing.GroupLayout(jpImagen);
        jpImagen.setLayout(jpImagenLayout);
        jpImagenLayout.setHorizontalGroup(
            jpImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jpImagenLayout.setVerticalGroup(
            jpImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jpImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbElegir, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbElegir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelar))
        );

        jtCasoClinico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtCasoClinico.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtCasoClinico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCasoClinicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtCasoClinico);

        jlBuscarCasoClinico.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jlBuscarCasoClinico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jlBuscarCasoClinico)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbElegirActionPerformed
        // TODO add your handling code here:
        //String colName[] = {"dni_duenio","nombre","apellido","email","facebook","domicilio","ciudad","telefono_fijo","telefono_celular"};
       
        int filamodificar= jtCasoClinico.getSelectedRow();
        if(filamodificar>=0){
        String protocolo_lab= jtCasoClinico.getValueAt(filamodificar, 0).toString();
        String reporte="Hemograma";
        jasper.ejecutarReporte(protocolo_lab,reporte);
        }
    }//GEN-LAST:event_jbElegirActionPerformed

    private void jtCasoClinicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCasoClinicoMouseClicked
        // TODO add your handling code here:
        fila=jtCasoClinico.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_jtCasoClinicoMouseClicked

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
                String texto= jtfBuscar.getText();
        String[] columNames = {"Protocolo Lab","Caso Clinico","DNI del Duenio","Apellido","Nombre","Nombre Del Animal"};
        String colName[] = {"protocolo_lab","caso_clinico","dni_duenio","apellido","nombre","animal_pequenios.nombre"};        //nombre de columnas, tabla, instruccion sql
        if(jrbProtocoloLab.isSelected()==true){
            dtCasoClinico = casoClinico.GetTabla(colName, "consulta,duenio,animal_pequenios,doctor,hemograma", "SELECT * FROM `consulta`,`duenio`,`animal_pequenios`,`doctor`,`hemograma` WHERE (`consulta`.`cod_animal` =`animal_pequenios`.`cod_animal`) AND (`consulta`.`dni_doctor` =`doctor`.`dni_doctor`) AND (`animal_pequenios`.`dni_duenio` =`duenio`.`dni_duenio`)AND (`consulta`.`caso_clinico` = `hemograma`.`caso_clinico`)AND(`hemograma`.`protocolo_lab`= \"" + texto + "\")");
        }
        if(jrbDni.isSelected()==true){

            dtCasoClinico = casoClinico.GetTabla(colName, "consulta,duenio,animal_pequenios,doctor,hemograma", "SELECT * FROM `consulta`,`duenio`,`animal_pequenios`,`doctor`,`hemograma` WHERE (`consulta`.`cod_animal` =`animal_pequenios`.`cod_animal`) AND (`consulta`.`dni_doctor` =`doctor`.`dni_doctor`) AND (`animal_pequenios`.`dni_duenio` =`duenio`.`dni_duenio`)AND (`consulta`.`caso_clinico` = `hemograma`.`caso_clinico`)AND(`duenio`.`dni_duenio`= \"" + texto + "\")");
        } 
        if(jrbNombreAnimal.isSelected()==true){

            dtCasoClinico = casoClinico.GetTabla(colName, "consulta,duenio,animal_pequenios,doctor,hemograma", "SELECT * FROM `consulta`,`duenio`,`animal_pequenios`,`doctor`,`hemograma` WHERE (`consulta`.`cod_animal` =`animal_pequenios`.`cod_animal`) AND (`consulta`.`dni_doctor` =`doctor`.`dni_doctor`) AND (`animal_pequenios`.`dni_duenio` =`duenio`.`dni_duenio`)AND (`consulta`.`caso_clinico` = `hemograma`.`caso_clinico`)AND(`animal_pequenios`.`nombre`= \"" + texto + "\")");
        }
        DefaultTableModel datos = new DefaultTableModel(dtCasoClinico,columNames);
        jtCasoClinico.setModel(datos);// se colocan los datos en la tabla
    //depurador de jtDuenio de item null
        int a = jtCasoClinico.getRowCount();        
        int i=0;
        a--;
        while(a>=i){
            if(jtCasoClinico.getValueAt(i,1)==null){
                ((DefaultTableModel)jtCasoClinico.getModel()).removeRow(i);
                a--;
                i--;
            }
            i++;
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    Object[][] dtCasoClinico;  
    MySQL casoClinico = new MySQL();
    int fila = -1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbElegir;
    public static javax.swing.JLabel jlBuscarCasoClinico;
    private javax.swing.JPanel jpImagen;
    private javax.swing.JRadioButton jrbDni;
    private javax.swing.JRadioButton jrbNombreAnimal;
    private javax.swing.JRadioButton jrbProtocoloLab;
    public static javax.swing.JTable jtCasoClinico;
    private javax.swing.JTextField jtfBuscar;
    // End of variables declaration//GEN-END:variables
}
