/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Consultas;

import Clases.MySQL;
import Clases.PantallaPrincipal;
import ModuloUsuario.ImgDoctor;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BayBay
 */
public class BuscarAlumnoDerivacionG extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminarAnimalP
     */
    public BuscarAlumnoDerivacionG() {
        initComponents();
        ImgDoctor img = new ImgDoctor();
        jpImagen.add(img);
        jpImagen.repaint();
        cargarTabla();
    }

    private void cargarTabla(){
        String[] columNames = {"Apellido", "Nombre", "DNI", "E-Mail", "Matricula", "Domicilio", "Ciudad", "Celular", "Tel.Fijo"};
        String colName[] = {"apellido", "nombre", "dni_alumno", "email", "matricula", "domicilio", "ciudad", "telefono_celular", "telefono_fijo"};
        //nombre de columnas, tabla, instruccion sql
        dtAlumno = alumno.GetTabla(colName, "alumno", "SELECT * FROM `alumno` ORDER BY `apellido`");
        // se colocan los datos en la tabla
        DefaultTableModel datos = new DefaultTableModel(dtAlumno, columNames);
        jtAlumno.setModel(datos);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jtfBuscar = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jrbApellido = new javax.swing.JRadioButton();
        jrbDni = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jbElegir = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jpImagen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAlumno = new javax.swing.JTable();

        setClosable(true);
        setTitle("Buscar Alumno");
        setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbApellido);
        jrbApellido.setText("Por apellido");

        buttonGroup1.add(jrbDni);
        jrbDni.setText("Por DNI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbApellido)
                    .addComponent(jrbDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrbApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbDni))
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jbElegir.setText("Elegir");
        jbElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbElegirActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jpImagen.setPreferredSize(new java.awt.Dimension(128, 128));

        javax.swing.GroupLayout jpImagenLayout = new javax.swing.GroupLayout(jpImagen);
        jpImagen.setLayout(jpImagenLayout);
        jpImagenLayout.setHorizontalGroup(
            jpImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jpImagenLayout.setVerticalGroup(
            jpImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jpImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jbElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jbCancelar)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbElegir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelar))
        );

        jtAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAlumnoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtAlumno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 124, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbElegirActionPerformed
        // TODO add your handling code here:
        //String colName[] = {"dni_duenio","nombre","apellido","email","facebook","domicilio","ciudad","telefono_fijo","telefono_celular"};
        int filamodificar= jtAlumno.getSelectedRow();
        if(filamodificar>=0){
        String apellido= jtAlumno.getValueAt(filamodificar, 0).toString();
        String nombre= jtAlumno.getValueAt(filamodificar, 1).toString();
        String dni= jtAlumno.getValueAt(filamodificar, 2).toString();
        DerivacionP.jlAlumno.setText(apellido);
        DerivacionP.jlAlumno1.setText(nombre);
        DerivacionP.jlAlumno2.setText(dni);
       
        }
        this.dispose();
    }//GEN-LAST:event_jbElegirActionPerformed

    private void jtAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAlumnoMouseClicked
        // TODO add your handling code here:
        fila=jtAlumno.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_jtAlumnoMouseClicked

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
                String texto= jtfBuscar.getText();
        String[] columNames = {"Apellido", "Nombre", "DNI", "E-Mail", "Matricula", "Domicilio", "Ciudad", "Celular", "Tel.Fijo"};
        String colName[] = {"apellido", "nombre", "dni_alumno", "email", "matricula", "domicilio", "ciudad", "telefono_celular", "telefono_fijo"};
        //nombre de columnas, tabla, instruccion sql
        if (jrbDni.isSelected() == true) {
            dtAlumno = alumno.GetTabla(colName, "alumno", "SELECT * FROM `duenio` WHERE `dni_alumno`=" + texto + " ");
        }
        if (jrbApellido.isSelected() == true) {

            dtAlumno = alumno.GetTabla(colName, "alumno", "SELECT * FROM `doctor` WHERE `apellido` = \"" + texto + "\"");
        }      
        DefaultTableModel datos = new DefaultTableModel(dtAlumno,columNames);
        jtAlumno.setModel(datos); // se colocan los datos en la tabla
    //depurador de jtDuenio de item null
        int a = jtAlumno.getRowCount();        
        int i=0;
        a--;
        while(a>=i){
            if(jtAlumno.getValueAt(i,1)==null){
                ((DefaultTableModel)jtAlumno.getModel()).removeRow(i);
                a--;
                i--;
            }
            i++;
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    Object[][] dtAlumno;  
    MySQL alumno = new MySQL();
    int fila = -1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbElegir;
    private javax.swing.JPanel jpImagen;
    private javax.swing.JRadioButton jrbApellido;
    private javax.swing.JRadioButton jrbDni;
    public static javax.swing.JTable jtAlumno;
    private javax.swing.JTextField jtfBuscar;
    // End of variables declaration//GEN-END:variables
}
