/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Consultas;

import Clases.MySQL;
import static Clases.PantallaPrincipal.jdpFondo;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Ale
 */
public class BuscarCasoClinico extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarCasoClinico
     */
    public BuscarCasoClinico() {
        initComponents();
        auxenviar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfCasoClinico = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfCasoClinico1 = new javax.swing.JTextField();
        auxenviar = new javax.swing.JLabel();

        setTitle("BUSCAR CASO CLINICO");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Ingrese el Número de Caso Clinico:");

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("/");

        auxenviar.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCasoClinico, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfCasoClinico1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jbBuscar)
                .addGap(33, 33, 33)
                .addComponent(auxenviar)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCasoClinico)
                    .addComponent(jbBuscar)
                    .addComponent(jLabel2)
                    .addComponent(tfCasoClinico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auxenviar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        String caso_clinico = tfCasoClinico.getText();
        
        SimpleDateFormat formatodeltexto = new SimpleDateFormat("yyyy");
        String fecha=tfCasoClinico1.getText();
        Date aux = null;
try {
        aux = formatodeltexto.parse(fecha);
} catch (ParseException ex) {
        ex.printStackTrace();
}
        String colName[] = {"caso_clinico"};
        
        boolean a = consulta.existe("consulta", "caso_clinico", caso_clinico);
        if (a==false){
            JOptionPane.showMessageDialog(rootPane, "El Caso Clinico no existe");
        }
        else{
            
            dtconsulta = consulta.GetTabla(colName,"consulta","SELECT * FROM `consulta`WHERE `fecha` BETWEEN '"+ aux +"-01-01'AND '"+ aux+"-12-31'");
            
            if (dtconsulta == null){
                        JOptionPane.showMessageDialog(rootPane, "El Caso Clinico no existe");}
            else {
                   this.dispose();
                   auxenviar.setText(tfCasoClinico.getText()); 
                   RetornoAnimalP retorno = new RetornoAnimalP();
                   jdpFondo.add(retorno);
                   retorno.show();
                   
            }
        }
        
    }//GEN-LAST:event_jbBuscarActionPerformed
    MySQL consulta = new MySQL();
    Object[][] dtconsulta; 
    int fila = -1;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel auxenviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JTextField tfCasoClinico;
    private javax.swing.JTextField tfCasoClinico1;
    // End of variables declaration//GEN-END:variables
}
