/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Consultas;


import Clases.MySQL;
import Clases.PantallaPrincipal;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author BayBay
 */
public class RetornoAnimalG extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaAnimalp
     */
    public RetornoAnimalG() {
        initComponents();
        Calendar Cal= Calendar.getInstance();
        int Max= Integer.parseInt(animal.GetData("caso_clinico", "SELECT MAX(caso_clinico) caso_clinico FROM consulta"));
        int num= Max +1;
        jlCasoClinico.setText(""+BuscarCasoClinicoG.auxenviarg.getText()+"/"+Cal.get(Cal.YEAR));
      
      
        
    
    String fec= Cal.get(Cal.DATE)+"/"+(Cal.get(Cal.MONTH)+1)+"/"+Cal.get(Cal.YEAR);
    String hor=Cal.get(Cal.HOUR_OF_DAY)+":"+Cal.get(Cal.MINUTE)+":"+Cal.get(Cal.SECOND);
    jlFecha.setText(fec);
   
    jlHora.setText(hor);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane37 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpGeneral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbDatosDueño = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jlFecha = new javax.swing.JLabel();
        jlHora = new javax.swing.JLabel();
        jlCasoClinico = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlDomicilio = new javax.swing.JLabel();
        jlTelefono = new javax.swing.JLabel();
        jlDocente = new javax.swing.JLabel();
        jlAlumno = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlFechaNacimiento = new javax.swing.JLabel();
        jlSexo = new javax.swing.JLabel();
        jlEspecie = new javax.swing.JLabel();
        jlRaza = new javax.swing.JLabel();
        jlPeso = new javax.swing.JLabel();
        jlDato = new javax.swing.JLabel();
        jBuscarPropietario = new javax.swing.JButton();
        jLabel143 = new javax.swing.JLabel();
        jlDni = new javax.swing.JLabel();
        jlColor = new javax.swing.JLabel();
        jlDocente1 = new javax.swing.JLabel();
        jlDocente2 = new javax.swing.JLabel();
        jBuscarDocente = new javax.swing.JButton();
        jlAlumno2 = new javax.swing.JLabel();
        jlAlumno1 = new javax.swing.JLabel();
        jBuscarAlumno = new javax.swing.JButton();
        jBuscarAnimal = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jtpPestañas = new javax.swing.JTabbedPane();
        jpRetorno1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaAnamnesis = new javax.swing.JTextArea();
        jpRetorno2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jtftemperatura = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jtfFC = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jtfFR = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jcbCC = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jcbLLCap = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jcbPulsoRitmo = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jcbPulsoIntensidad = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jcbHidratacion = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jcbMaOcular = new javax.swing.JComboBox();
        jcbMaBucal = new javax.swing.JComboBox();
        jcbMaNasal = new javax.swing.JComboBox();
        jcbMaGenital = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jcbSubmandibular1 = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jcbAxilar1 = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jcbInguinales1 = new javax.swing.JComboBox();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jcbPopliteos1 = new javax.swing.JComboBox();
        jpDeshidratado = new javax.swing.JPanel();
        jpSubmandibular = new javax.swing.JPanel();
        jpAxilar = new javax.swing.JPanel();
        jpInguinales = new javax.swing.JPanel();
        jpPopliteos = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jtfDeshidratado = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jcbSubmandibular2 = new javax.swing.JComboBox();
        jcbSubmandibular3 = new javax.swing.JComboBox();
        jcbSubmandibular4 = new javax.swing.JComboBox();
        jLabel41 = new javax.swing.JLabel();
        jcbAxilar2 = new javax.swing.JComboBox();
        jcbAxilar3 = new javax.swing.JComboBox();
        jcbAxilar4 = new javax.swing.JComboBox();
        jLabel44 = new javax.swing.JLabel();
        jcbInguinales2 = new javax.swing.JComboBox();
        jcbInguinales3 = new javax.swing.JComboBox();
        jcbInguinales4 = new javax.swing.JComboBox();
        jLabel47 = new javax.swing.JLabel();
        jcbPopliteos2 = new javax.swing.JComboBox();
        jcbPopliteos3 = new javax.swing.JComboBox();
        jcbPopliteos4 = new javax.swing.JComboBox();
        jpRetorno3 = new javax.swing.JPanel();
        jpParalisis = new javax.swing.JPanel();
        jpConvulsion = new javax.swing.JPanel();
        jpParesia = new javax.swing.JPanel();
        jLabel126 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaSistema = new javax.swing.JTextArea();
        jpConsulta10 = new javax.swing.JPanel();
        jLabel116 = new javax.swing.JLabel();
        jScrollPane35 = new javax.swing.JScrollPane();
        jtaIndicaciones = new javax.swing.JTextArea();

        setClosable(true);
        setResizable(true);
        setTitle("CREAR RETORNO ANIMALES GRANDES");
        setAutoscrolls(true);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(500, 958));

        jpGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RETORNO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jpGeneral.setMaximumSize(new java.awt.Dimension(813, 259));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Fecha:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Hora:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CASO CLINICO Nº:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Propietario:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Domicilio:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Telefono:");

        jcbDatosDueño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "e-mail", "facebook", "celular", " " }));
        jcbDatosDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDatosDueñoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Docente Responsable del caso:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Alumno Responsable del caso:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Nombre:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Fecha nacimiento:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Especie:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Raza:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Peso:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Sexo:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Color:");

        jlFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlFecha.setText("fecha");

        jlHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlHora.setText("hora");

        jlCasoClinico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCasoClinico.setText("caso clinico");

        jlApellido.setText("apellido");

        jlDomicilio.setText("domicilio");

        jlTelefono.setText("telefono");

        jlDocente.setText("docente");

        jlAlumno.setText("alumno");

        jlNombre.setText("nombre");

        jlFechaNacimiento.setText("fecha");

        jlSexo.setText("sexo");

        jlEspecie.setText("especie");

        jlRaza.setText("raza");

        jlPeso.setText("peso");

        jlDato.setText("dato");

        jBuscarPropietario.setText("Buscar Propietario");
        jBuscarPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarPropietarioActionPerformed(evt);
            }
        });

        jLabel143.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel143.setText("DNI:");

        jlDni.setText("dni");

        jlColor.setText("color");

        jlDocente1.setText("docente");

        jlDocente2.setText("docente");

        jBuscarDocente.setText("Buscar Docente");
        jBuscarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarDocenteActionPerformed(evt);
            }
        });

        jlAlumno2.setText("alumno");

        jlAlumno1.setText("alumno");

        jBuscarAlumno.setText("Buscar Alumno");
        jBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarAlumnoActionPerformed(evt);
            }
        });

        jBuscarAnimal.setText("Buscar Animal");
        jBuscarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarAnimalActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Contacto");

        jLabel123.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel123.setText("DATOS DEL PROPIETARIO");

        jLabel124.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel124.setText("DATOS DEL ANIMAL");

        jLabel125.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel125.setText("DATOS DE RESPONSABLES DE LA CONSULTA");

        jbGuardar.setText("Guardar Consulta");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");

        javax.swing.GroupLayout jpGeneralLayout = new javax.swing.GroupLayout(jpGeneral);
        jpGeneral.setLayout(jpGeneralLayout);
        jpGeneralLayout.setHorizontalGroup(
            jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGeneralLayout.createSequentialGroup()
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpGeneralLayout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jlFecha))
                            .addComponent(jLabel1)
                            .addGroup(jpGeneralLayout.createSequentialGroup()
                                .addGap(264, 264, 264)
                                .addComponent(jLabel2)
                                .addGap(34, 34, 34)
                                .addComponent(jlHora)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlCasoClinico)
                        .addGap(571, 571, 571))
                    .addGroup(jpGeneralLayout.createSequentialGroup()
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpGeneralLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlApellido))
                            .addGroup(jpGeneralLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlTelefono))
                            .addComponent(jLabel123)
                            .addGroup(jpGeneralLayout.createSequentialGroup()
                                .addComponent(jLabel143)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlDni))
                            .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jBuscarPropietario)
                                .addGroup(jpGeneralLayout.createSequentialGroup()
                                    .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpGeneralLayout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jlDomicilio))
                                        .addGroup(jpGeneralLayout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jcbDatosDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jlDato))))
                        .addGap(136, 136, 136)
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpGeneralLayout.createSequentialGroup()
                                .addComponent(jLabel124)
                                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpGeneralLayout.createSequentialGroup()
                                        .addGap(227, 227, 227)
                                        .addComponent(jlDocente1)
                                        .addGap(63, 63, 63)
                                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlAlumno2)
                                            .addComponent(jlDocente2)))
                                    .addGroup(jpGeneralLayout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(jLabel125))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jBuscarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpGeneralLayout.createSequentialGroup()
                                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jpGeneralLayout.createSequentialGroup()
                                                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jpGeneralLayout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jlNombre))
                                                    .addGroup(jpGeneralLayout.createSequentialGroup()
                                                        .addComponent(jLabel12)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jlEspecie))
                                                    .addComponent(jLabel11)
                                                    .addGroup(jpGeneralLayout.createSequentialGroup()
                                                        .addComponent(jLabel14)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jlPeso))
                                                    .addGroup(jpGeneralLayout.createSequentialGroup()
                                                        .addComponent(jLabel13)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jlRaza))
                                                    .addGroup(jpGeneralLayout.createSequentialGroup()
                                                        .addComponent(jLabel15)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jlSexo))
                                                    .addGroup(jpGeneralLayout.createSequentialGroup()
                                                        .addComponent(jLabel16)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jlColor)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jlFechaNacimiento))
                                            .addComponent(jBuscarAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(113, 113, 113)
                                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jlDocente)
                                            .addGroup(jpGeneralLayout.createSequentialGroup()
                                                .addComponent(jlAlumno)
                                                .addGap(90, 90, 90)
                                                .addComponent(jlAlumno1))
                                            .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGeneralLayout.createSequentialGroup()
                                        .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(140, 140, 140)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jpGeneralLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpGeneralLayout.setVerticalGroup(
            jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jlFecha)
                        .addComponent(jlHora))
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jlCasoClinico)))
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGeneralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel123)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jpGeneralLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel124)
                            .addComponent(jLabel125))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jlNombre)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jlApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel143)
                    .addComponent(jlDni)
                    .addComponent(jLabel12)
                    .addComponent(jlEspecie)
                    .addComponent(jlDocente)
                    .addComponent(jlDocente1)
                    .addComponent(jlDocente2))
                .addGap(11, 11, 11)
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlDomicilio)
                    .addComponent(jLabel13)
                    .addComponent(jlRaza)
                    .addComponent(jBuscarDocente))
                .addGap(2, 2, 2)
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcbDatosDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDato)
                    .addComponent(jlPeso)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jlTelefono)
                    .addComponent(jlFechaNacimiento)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8))
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGeneralLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jlAlumno1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBuscarPropietario)
                            .addComponent(jBuscarAlumno)))
                    .addGroup(jpGeneralLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jlAlumno2))
                    .addGroup(jpGeneralLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jlSexo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jlColor)
                            .addComponent(jlAlumno))
                        .addGap(18, 18, 18)
                        .addComponent(jBuscarAnimal)))
                .addGap(77, 77, 77)
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addGroup(jpGeneralLayout.createSequentialGroup()
                        .addComponent(jbSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)))
                .addGap(506, 506, 506))
        );

        jTabbedPane1.addTab("General", jpGeneral);

        jtpPestañas.setAutoscrolls(true);

        jpRetorno1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Retorno 1/5", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jpRetorno1.setPreferredSize(new java.awt.Dimension(728, 630));

        jLabel18.setText("Anamnesis:");

        jtaAnamnesis.setColumns(20);
        jtaAnamnesis.setRows(5);
        jScrollPane2.setViewportView(jtaAnamnesis);

        javax.swing.GroupLayout jpRetorno1Layout = new javax.swing.GroupLayout(jpRetorno1);
        jpRetorno1.setLayout(jpRetorno1Layout);
        jpRetorno1Layout.setHorizontalGroup(
            jpRetorno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRetorno1Layout.createSequentialGroup()
                .addGroup(jpRetorno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jpRetorno1Layout.setVerticalGroup(
            jpRetorno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRetorno1Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(705, Short.MAX_VALUE))
        );

        jtpPestañas.addTab("PARTE 1", jpRetorno1);

        jpRetorno2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Retorno 2/5", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jpRetorno2.setPreferredSize(new java.awt.Dimension(728, 630));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Constantes Fisiológicas:");

        jLabel20.setText("Temperatura:");

        jLabel21.setText("Frecuencia Cardiaca:");

        jLabel22.setText("Frecuencia Respiratoria:");

        jtfFR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFRActionPerformed(evt);
            }
        });

        jLabel23.setText("CC:");

        jcbCC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        jLabel24.setText("LL. Cap.:");

        jcbLLCap.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rapido", "Normal", "Lento" }));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Pulso");

        jcbPulsoRitmo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Regular", "Irregular" }));
        jcbPulsoRitmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPulsoRitmoActionPerformed(evt);
            }
        });

        jLabel26.setText("Ritmo:");

        jLabel27.setText("Intensidad:");

        jcbPulsoIntensidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fuerte", "Normal", "Debil" }));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Hidratacion:");

        jcbHidratacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Deshidratado" }));
        jcbHidratacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHidratacionActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Mucosas Aparentes:");

        jLabel31.setText("Ocular:");

        jLabel32.setText("Bucal:");

        jLabel33.setText("Nasal:");

        jLabel34.setText("Genital:");

        jcbMaOcular.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rosa normal", "Palida", "Icterica", "Cianotica", "Hiperemica" }));

        jcbMaBucal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rosa normal", "Palida", "Icterica", "Cianotica", "Hiperemica" }));

        jcbMaNasal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rosa normal", "Palida", "Icterica", "Cianotica", "Hiperemica" }));

        jcbMaGenital.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rosa normal", "Palida", "Icterica", "Cianotica", "Hiperemica" }));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setText("Ganglios Linfaticos:");

        jLabel36.setText("Submandibular:");

        jcbSubmandibular1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        jcbSubmandibular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSubmandibular1ActionPerformed(evt);
            }
        });

        jLabel37.setText("Normal");

        jLabel39.setText("Axilar:");

        jLabel40.setText("Normal");

        jcbAxilar1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        jcbAxilar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAxilar1ActionPerformed(evt);
            }
        });

        jLabel42.setText("Inguinales:");

        jLabel43.setText("Normal");

        jcbInguinales1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        jcbInguinales1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbInguinales1ActionPerformed(evt);
            }
        });

        jLabel45.setText("Popliteos:");

        jLabel46.setText("Normal");

        jcbPopliteos1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        jcbPopliteos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPopliteos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDeshidratadoLayout = new javax.swing.GroupLayout(jpDeshidratado);
        jpDeshidratado.setLayout(jpDeshidratadoLayout);
        jpDeshidratadoLayout.setHorizontalGroup(
            jpDeshidratadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jpDeshidratadoLayout.setVerticalGroup(
            jpDeshidratadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpSubmandibularLayout = new javax.swing.GroupLayout(jpSubmandibular);
        jpSubmandibular.setLayout(jpSubmandibularLayout);
        jpSubmandibularLayout.setHorizontalGroup(
            jpSubmandibularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpSubmandibularLayout.setVerticalGroup(
            jpSubmandibularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpAxilarLayout = new javax.swing.GroupLayout(jpAxilar);
        jpAxilar.setLayout(jpAxilarLayout);
        jpAxilarLayout.setHorizontalGroup(
            jpAxilarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpAxilarLayout.setVerticalGroup(
            jpAxilarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpInguinalesLayout = new javax.swing.GroupLayout(jpInguinales);
        jpInguinales.setLayout(jpInguinalesLayout);
        jpInguinalesLayout.setHorizontalGroup(
            jpInguinalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        jpInguinalesLayout.setVerticalGroup(
            jpInguinalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpPopliteosLayout = new javax.swing.GroupLayout(jpPopliteos);
        jpPopliteos.setLayout(jpPopliteosLayout);
        jpPopliteosLayout.setHorizontalGroup(
            jpPopliteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        jpPopliteosLayout.setVerticalGroup(
            jpPopliteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jLabel29.setText("si esta deshidratado %");

        jLabel38.setText("si es no:");

        jcbSubmandibular2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Duros", "Blandos" }));

        jcbSubmandibular3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Regulares", "Irregulares" }));

        jcbSubmandibular4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grandes", "Chicos" }));

        jLabel41.setText("si es no:");

        jcbAxilar2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Duros", "Blandos" }));

        jcbAxilar3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Regulares", "Irregulares" }));

        jcbAxilar4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grandes", "Chicos" }));

        jLabel44.setText("si es no:");

        jcbInguinales2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Duros", "Blandos" }));

        jcbInguinales3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Regulares", "Irregulares" }));

        jcbInguinales4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grandes", "Chicos" }));

        jLabel47.setText("si es no:");

        jcbPopliteos2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Duros", "Blandos" }));

        jcbPopliteos3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Regulares", "Irregulares" }));

        jcbPopliteos4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grandes", "Chicos" }));

        javax.swing.GroupLayout jpRetorno2Layout = new javax.swing.GroupLayout(jpRetorno2);
        jpRetorno2.setLayout(jpRetorno2Layout);
        jpRetorno2Layout.setHorizontalGroup(
            jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRetorno2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                        .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel30)
                            .addGroup(jpRetorno2Layout.createSequentialGroup()
                                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel32)
                                        .addComponent(jLabel31))
                                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel33))
                                    .addComponent(jLabel34))
                                .addGap(30, 30, 30)
                                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbMaNasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbMaGenital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbMaBucal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbMaOcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpRetorno2Layout.createSequentialGroup()
                                .addComponent(jcbHidratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDeshidratado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpRetorno2Layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                                        .addComponent(jcbSubmandibular1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel38))
                                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                                        .addComponent(jcbAxilar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel41)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                                        .addComponent(jcbSubmandibular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbSubmandibular3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                                        .addComponent(jcbAxilar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbAxilar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jpRetorno2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel35)
                                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                                        .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel39)
                                            .addComponent(jLabel42)
                                            .addComponent(jLabel45)
                                            .addComponent(jLabel36))
                                        .addGap(18, 18, 18)
                                        .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel37)
                                            .addComponent(jLabel40)
                                            .addComponent(jLabel43)
                                            .addComponent(jLabel46))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                                        .addComponent(jcbInguinales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel44)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbInguinales2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbInguinales3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                                        .addComponent(jcbPopliteos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel47)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbPopliteos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbPopliteos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jpDeshidratado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbSubmandibular4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbAxilar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbInguinales4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbPopliteos4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                        .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpRetorno2Layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jpPopliteos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jpAxilar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jpSubmandibular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jpRetorno2Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(jpInguinales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addGroup(jpRetorno2Layout.createSequentialGroup()
                                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtftemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jpRetorno2Layout.createSequentialGroup()
                                            .addComponent(jLabel26)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jcbPulsoRitmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpRetorno2Layout.createSequentialGroup()
                                            .addComponent(jLabel27)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jcbPulsoIntensidad, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(52, 52, 52)
                                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfFC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbLLCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, 7)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfFR, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                        .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel25))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpRetorno2Layout.setVerticalGroup(
            jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRetorno2Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jtftemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jtfFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jtfFR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jcbCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jcbLLCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addGap(11, 11, 11)
                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jcbPulsoIntensidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jcbPulsoRitmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbHidratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(jtfDeshidratado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(jcbMaOcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)
                            .addComponent(jcbSubmandibular1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38)
                            .addComponent(jcbSubmandibular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbSubmandibular3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbSubmandibular4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jcbMaBucal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)
                            .addComponent(jcbAxilar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41)
                            .addComponent(jcbAxilar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbAxilar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbAxilar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jcbMaNasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42)
                            .addComponent(jLabel43)
                            .addComponent(jcbInguinales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44)
                            .addComponent(jcbInguinales2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbInguinales3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbInguinales4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcbMaGenital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel34))
                            .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel45)
                                .addComponent(jLabel46)
                                .addComponent(jcbPopliteos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel47)
                                .addComponent(jcbPopliteos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbPopliteos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbPopliteos4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jpDeshidratado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpAxilar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                        .addComponent(jpSubmandibular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGap(29, 29, 29)
                .addGroup(jpRetorno2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRetorno2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jpPopliteos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpInguinales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpPestañas.addTab("PARTE 2", jpRetorno2);

        jpRetorno3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Retorno 3/5", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jpRetorno3.setPreferredSize(new java.awt.Dimension(728, 630));

        javax.swing.GroupLayout jpParalisisLayout = new javax.swing.GroupLayout(jpParalisis);
        jpParalisis.setLayout(jpParalisisLayout);
        jpParalisisLayout.setHorizontalGroup(
            jpParalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpParalisisLayout.setVerticalGroup(
            jpParalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpConvulsionLayout = new javax.swing.GroupLayout(jpConvulsion);
        jpConvulsion.setLayout(jpConvulsionLayout);
        jpConvulsionLayout.setHorizontalGroup(
            jpConvulsionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        jpConvulsionLayout.setVerticalGroup(
            jpConvulsionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpParesiaLayout = new javax.swing.GroupLayout(jpParesia);
        jpParesia.setLayout(jpParesiaLayout);
        jpParesiaLayout.setHorizontalGroup(
            jpParesiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpParesiaLayout.setVerticalGroup(
            jpParesiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jLabel126.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel126.setText("SISTEMA EVALUADO Y DATOS ENCONTRADOS");

        jtaSistema.setColumns(20);
        jtaSistema.setRows(5);
        jScrollPane1.setViewportView(jtaSistema);

        javax.swing.GroupLayout jpRetorno3Layout = new javax.swing.GroupLayout(jpRetorno3);
        jpRetorno3.setLayout(jpRetorno3Layout);
        jpRetorno3Layout.setHorizontalGroup(
            jpRetorno3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRetorno3Layout.createSequentialGroup()
                .addGroup(jpRetorno3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRetorno3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRetorno3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpConvulsion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpRetorno3Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jpRetorno3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpParalisis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jpParesia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jpRetorno3Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel126)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpRetorno3Layout.setVerticalGroup(
            jpRetorno3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRetorno3Layout.createSequentialGroup()
                .addComponent(jLabel126)
                .addGroup(jpRetorno3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRetorno3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jpRetorno3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpRetorno3Layout.createSequentialGroup()
                                .addComponent(jpParalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addComponent(jpParesia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpConvulsion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpRetorno3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 645, Short.MAX_VALUE))
        );

        jtpPestañas.addTab("PARTE 9", jpRetorno3);

        jpConsulta10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta 10/10", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jpConsulta10.setPreferredSize(new java.awt.Dimension(728, 630));

        jLabel116.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel116.setText("INDICACIONES AL PROPIETARIO/RESPONSABLE");

        jtaIndicaciones.setColumns(20);
        jtaIndicaciones.setRows(5);
        jScrollPane35.setViewportView(jtaIndicaciones);

        javax.swing.GroupLayout jpConsulta10Layout = new javax.swing.GroupLayout(jpConsulta10);
        jpConsulta10.setLayout(jpConsulta10Layout);
        jpConsulta10Layout.setHorizontalGroup(
            jpConsulta10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsulta10Layout.createSequentialGroup()
                .addGroup(jpConsulta10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConsulta10Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel116))
                    .addGroup(jpConsulta10Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jpConsulta10Layout.setVerticalGroup(
            jpConsulta10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsulta10Layout.createSequentialGroup()
                .addComponent(jLabel116)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(743, Short.MAX_VALUE))
        );

        jtpPestañas.addTab("PARTE 10", jpConsulta10);

        jTabbedPane1.addTab("Detalles", jtpPestañas);

        jScrollPane37.setViewportView(jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane37, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane37, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jtfFRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFRActionPerformed

    private void jcbPulsoRitmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPulsoRitmoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPulsoRitmoActionPerformed

    private void jcbHidratacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHidratacionActionPerformed
        // TODO add your handling code here:
        String hidratado="Deshidratado";
        String hidratado2=(String)jcbHidratacion.getSelectedItem();
        if (hidratado2==hidratado){
            jpDeshidratado.setVisible(true);
        }else{
            jpDeshidratado.setVisible(false);
        }
    }//GEN-LAST:event_jcbHidratacionActionPerformed

    private void jcbSubmandibular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSubmandibular1ActionPerformed
        // TODO add your handling code here:    
        String submandibular = (String)jcbSubmandibular1.getSelectedItem();
        String submandibular2 = "No";
        if(submandibular==submandibular2){
            jpSubmandibular.setVisible(true);
        }else{
            jpSubmandibular.setVisible(false);
        }
    }//GEN-LAST:event_jcbSubmandibular1ActionPerformed

    private void jcbAxilar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAxilar1ActionPerformed
        // TODO add your handling code here:
        String axilar = (String)jcbAxilar1.getSelectedItem();
        String axilar2 = "No";
        if(axilar==axilar2){
            jpAxilar.setVisible(true);
        }else{
            jpAxilar.setVisible(false);
        }
    }//GEN-LAST:event_jcbAxilar1ActionPerformed

    private void jcbInguinales1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbInguinales1ActionPerformed
        // TODO add your handling code here:
        String inguinales = (String)jcbInguinales1.getSelectedItem();
        String inguinales2 = "No";
        if(inguinales==inguinales2){
            jpInguinales.setVisible(true);
        }else{
            jpInguinales.setVisible(false);
        }
    }//GEN-LAST:event_jcbInguinales1ActionPerformed

    private void jcbPopliteos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPopliteos1ActionPerformed
        // TODO add your handling code here:
        String popliteos = (String)jcbPopliteos1.getSelectedItem();
        String popliteos2 = "No";
        if(popliteos==popliteos2){
            jpPopliteos.setVisible(true);
        }else{
            jpPopliteos.setVisible(false);
        }
    }//GEN-LAST:event_jcbPopliteos1ActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
          
            String caso_clinico = jlCasoClinico.getText();
            //* Buscamos el ultimo cod_retorno y se suma 1 es decir, si el ultimo es 2 , se guarda 3
            int Max= Integer.parseInt(animal.GetData("cod_retorno", "SELECT MAX(cod_retorno) cod_retorno FROM retornog"));
            String cod_retorno= Integer.toString(Max+1);
            
            String cod_animal="1";
            String dni_doctor=jlDocente2.getText();
            String dni_alumno=jlAlumno2.getText();
           
        boolean aux = animal.existe("retornog", "cod_retorno", cod_retorno);
        if (aux==true){
            JOptionPane.showMessageDialog(rootPane, "El registro ya existe");
        }else{
           
            String anamnesis = jtaAnamnesis.getText();
            String temperatura = jtftemperatura.getText();
            String fc = jtfFC.getText();
            String fr = jtfFR.getText();
            String cc = (String)jcbCC.getSelectedItem();
            String ll_cap = (String)jcbLLCap.getSelectedItem();
            String pulso_ritmo = (String)jcbPulsoRitmo.getSelectedItem();
            String pulso_intensidad = (String)jcbPulsoIntensidad.getSelectedItem();
            String hidratacion2="Deshidratado";
        String hidratacion=(String)jcbHidratacion.getSelectedItem();
        if (hidratacion2==hidratacion){
            hidratacion = jtfDeshidratado.getText();
        }else{
            hidratacion=(String)jcbHidratacion.getSelectedItem();
        }
            String ma_ocular = (String)jcbMaOcular.getSelectedItem();
            String ma_bucal = (String)jcbMaBucal.getSelectedItem();
            String ma_nasal = (String)jcbMaNasal.getSelectedItem();
            String ma_genital = (String)jcbMaGenital.getSelectedItem();
            String submandibular = (String)jcbSubmandibular1.getSelectedItem();
            String submandibular2 = "No";
        if(submandibular==submandibular2){
            submandibular = (String)jcbSubmandibular2.getSelectedItem()+","+jcbSubmandibular3.getSelectedItem()+","+jcbSubmandibular4.getSelectedItem();
        }else{
            submandibular = "Si";
        }
        String axilar = (String)jcbAxilar1.getSelectedItem();
            String axilar2 = "No";
        if(axilar==axilar2){
            axilar = (String)jcbAxilar2.getSelectedItem()+","+jcbAxilar3.getSelectedItem()+","+jcbAxilar4.getSelectedItem();
        }else{
            axilar = "Si";
        }
        String inguinales = (String)jcbInguinales1.getSelectedItem();
            String inguinales2 = "No";
        if(inguinales==inguinales2){
            inguinales = (String)jcbInguinales2.getSelectedItem()+","+jcbInguinales3.getSelectedItem()+","+jcbInguinales4.getSelectedItem();
        }else{
            inguinales = "Si";
        }
        String popliteos = (String)jcbPopliteos1.getSelectedItem();
            String popliteos2 = "No";
        if(popliteos==popliteos2){
            popliteos = (String)jcbPopliteos2.getSelectedItem()+","+jcbPopliteos3.getSelectedItem()+","+jcbPopliteos4.getSelectedItem();
        }else{
            popliteos = "Si";
        }
            
        String indicaciones = jtaIndicaciones.getText();
        
        java.util.Date date = new java.util.Date();
        java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("yyyy-MM-dd");
        String fecha = sdf.format(date);
        String datos[] = {cod_retorno,caso_clinico,fecha,cod_animal,dni_doctor,dni_alumno,anamnesis,temperatura,fc,fr,cc,ll_cap,pulso_ritmo,pulso_intensidad,hidratacion,ma_ocular,ma_bucal,ma_nasal,ma_genital,submandibular,axilar,inguinales,popliteos,indicaciones};
         
         
         
            
           animal.InsertarRegistro(datos, "insert into retornog values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
        }
    
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarAlumnoActionPerformed
        // TODO add your handling code here:
        BuscarAlumnoRetornoG buscarAlumno = new BuscarAlumnoRetornoG();
        PantallaPrincipal.jdpFondo.add(buscarAlumno);
        buscarAlumno.toFront();
        buscarAlumno.setVisible(true);
    }//GEN-LAST:event_jBuscarAlumnoActionPerformed

    private void jBuscarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarDocenteActionPerformed
        // TODO add your handling code here:
        BuscarDocenteRetornoG buscarDocente = new BuscarDocenteRetornoG();
        PantallaPrincipal.jdpFondo.add(buscarDocente);
        buscarDocente.toFront();
        buscarDocente.setVisible(true);
    }//GEN-LAST:event_jBuscarDocenteActionPerformed

    private void jBuscarPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarPropietarioActionPerformed
        // TODO add your handling code here:
        BuscarDueñoRetornoG buscar = new BuscarDueñoRetornoG();
        PantallaPrincipal.jdpFondo.add(buscar);
        buscar.toFront();
        buscar.setVisible(true);
    }//GEN-LAST:event_jBuscarPropietarioActionPerformed

    private void jcbDatosDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDatosDueñoActionPerformed
        // TODO add your handling code here:
        String dni= jlDni.getText();
        String dato = jcbDatosDueño.getSelectedItem().toString();
        if(dato=="e-mail"){
            jlDato.setText(animal.GetData("email","SELECT email FROM duenio WHERE dni_duenio = \""+dni+"\""));
        }
        if(dato=="facebook"){
            jlDato.setText(animal.GetData("facebook","SELECT facebook FROM duenio WHERE dni_duenio = \""+dni+"\""));
        }
        if(dato=="celular"){
            jlDato.setText(animal.GetData("telefono_celular","SELECT telefono_celular FROM duenio WHERE dni_duenio = \""+dni+"\""));
        }
    }//GEN-LAST:event_jcbDatosDueñoActionPerformed

    private void jBuscarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBuscarAnimalActionPerformed

    MySQL animal = new MySQL();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBuscarAlumno;
    public javax.swing.JButton jBuscarAnimal;
    public javax.swing.JButton jBuscarDocente;
    public javax.swing.JButton jBuscarPropietario;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel116;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel123;
    public javax.swing.JLabel jLabel124;
    public javax.swing.JLabel jLabel125;
    public javax.swing.JLabel jLabel126;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel143;
    public javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel29;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel31;
    public javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel34;
    public javax.swing.JLabel jLabel35;
    public javax.swing.JLabel jLabel36;
    public javax.swing.JLabel jLabel37;
    public javax.swing.JLabel jLabel38;
    public javax.swing.JLabel jLabel39;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel40;
    public javax.swing.JLabel jLabel41;
    public javax.swing.JLabel jLabel42;
    public javax.swing.JLabel jLabel43;
    public javax.swing.JLabel jLabel44;
    public javax.swing.JLabel jLabel45;
    public javax.swing.JLabel jLabel46;
    public javax.swing.JLabel jLabel47;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane35;
    public static javax.swing.JScrollPane jScrollPane37;
    public static javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JButton jbGuardar;
    public javax.swing.JButton jbSalir;
    public javax.swing.JComboBox jcbAxilar1;
    public javax.swing.JComboBox jcbAxilar2;
    public javax.swing.JComboBox jcbAxilar3;
    public javax.swing.JComboBox jcbAxilar4;
    public javax.swing.JComboBox jcbCC;
    public javax.swing.JComboBox jcbDatosDueño;
    public javax.swing.JComboBox jcbHidratacion;
    public javax.swing.JComboBox jcbInguinales1;
    public javax.swing.JComboBox jcbInguinales2;
    public javax.swing.JComboBox jcbInguinales3;
    public javax.swing.JComboBox jcbInguinales4;
    public javax.swing.JComboBox jcbLLCap;
    public javax.swing.JComboBox jcbMaBucal;
    public javax.swing.JComboBox jcbMaGenital;
    public javax.swing.JComboBox jcbMaNasal;
    public javax.swing.JComboBox jcbMaOcular;
    public javax.swing.JComboBox jcbPopliteos1;
    public javax.swing.JComboBox jcbPopliteos2;
    public javax.swing.JComboBox jcbPopliteos3;
    public javax.swing.JComboBox jcbPopliteos4;
    public javax.swing.JComboBox jcbPulsoIntensidad;
    public javax.swing.JComboBox jcbPulsoRitmo;
    public javax.swing.JComboBox jcbSubmandibular1;
    public javax.swing.JComboBox jcbSubmandibular2;
    public javax.swing.JComboBox jcbSubmandibular3;
    public javax.swing.JComboBox jcbSubmandibular4;
    public static javax.swing.JLabel jlAlumno;
    public static javax.swing.JLabel jlAlumno1;
    public static javax.swing.JLabel jlAlumno2;
    public static javax.swing.JLabel jlApellido;
    public javax.swing.JLabel jlCasoClinico;
    public static javax.swing.JLabel jlColor;
    public javax.swing.JLabel jlDato;
    public static javax.swing.JLabel jlDni;
    public static javax.swing.JLabel jlDocente;
    public static javax.swing.JLabel jlDocente1;
    public static javax.swing.JLabel jlDocente2;
    public static javax.swing.JLabel jlDomicilio;
    public static javax.swing.JLabel jlEspecie;
    public javax.swing.JLabel jlFecha;
    public static javax.swing.JLabel jlFechaNacimiento;
    public javax.swing.JLabel jlHora;
    public static javax.swing.JLabel jlNombre;
    public static javax.swing.JLabel jlPeso;
    public static javax.swing.JLabel jlRaza;
    public static javax.swing.JLabel jlSexo;
    public static javax.swing.JLabel jlTelefono;
    public javax.swing.JPanel jpAxilar;
    public javax.swing.JPanel jpConsulta10;
    public javax.swing.JPanel jpConvulsion;
    public javax.swing.JPanel jpDeshidratado;
    public static javax.swing.JPanel jpGeneral;
    public javax.swing.JPanel jpInguinales;
    public javax.swing.JPanel jpParalisis;
    public javax.swing.JPanel jpParesia;
    public javax.swing.JPanel jpPopliteos;
    public javax.swing.JPanel jpRetorno1;
    public javax.swing.JPanel jpRetorno2;
    public javax.swing.JPanel jpRetorno3;
    public javax.swing.JPanel jpSubmandibular;
    public javax.swing.JTextArea jtaAnamnesis;
    public javax.swing.JTextArea jtaIndicaciones;
    public javax.swing.JTextArea jtaSistema;
    public javax.swing.JTextField jtfDeshidratado;
    public javax.swing.JTextField jtfFC;
    public javax.swing.JTextField jtfFR;
    public javax.swing.JTextField jtftemperatura;
    public javax.swing.JTabbedPane jtpPestañas;
    // End of variables declaration//GEN-END:variables
}
