/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Clases;

import Consultas.BuscarCasoClinico;
import Consultas.BuscarCasoClinicoG;
import Consultas.ConsultaAnimalG;
import Consultas.ConsultaAnimalP;
import Consultas.DerivacionP;
import Consultas.RetornoAnimalP;
import Examenes.Hemograma;
import Examenes.QuimicaClinica;
import Examenes.Urianalisis;
import ModuloAnimal.BuscarAnimalP;
import ModuloAnimal.EspecieRazaAnimalG;
import ModuloAnimal.EspecieRazaAnimalP;
import ModuloAnimal.ModificarAnimalG;
import ModuloAnimal.ModificarAnimalP;
import ModuloAnimal.NuevoAnimalG;
import ModuloAnimal.NuevoAnimalP;
import ModuloDueño.EliminarDueño;
import ModuloDueño.ModificarDueño;
import ModuloDueño.NuevoDueño;
import ModuloUsuario.ModificarAlumno;
import ModuloUsuario.ModificarDoctor;
import ModuloUsuario.NuevoAlumno;
import ModuloUsuario.NuevoDoctor;
import Reportes.BuscarHemograma;
import Reportes.BuscarQuimicaClinica;
import Reportes.BuscarUrianalisis;
import Reportes.EstadisticaAnalisisDocenteAlumno;
import javax.swing.JFrame;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author Ale
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        Logo img = new Logo ();
        jpLogo.add(img);
        jpLogo.repaint();
       
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jdpFondo = new javax.swing.JDesktopPane();
        jpLogo = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSistema = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();
        jMenuDuenio = new javax.swing.JMenu();
        jmiNuevoDuenio = new javax.swing.JMenuItem();
        jmiEliminarDueño = new javax.swing.JMenuItem();
        jmiModificarDueño = new javax.swing.JMenuItem();
        jMenuAnimal = new javax.swing.JMenu();
        jmiNuevoAnimalP = new javax.swing.JMenuItem();
        jmiModificarAnimalP = new javax.swing.JMenuItem();
        jmiEliminarAnimalP = new javax.swing.JMenuItem();
        jmiNuevoAnimalG = new javax.swing.JMenuItem();
        jmiModificarAnimalG = new javax.swing.JMenuItem();
        jmiNuevaRaza = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuDoctor = new javax.swing.JMenu();
        jmiNuevoDoctor = new javax.swing.JMenuItem();
        jmiModificarDoctor = new javax.swing.JMenuItem();
        jMenuAlumno = new javax.swing.JMenu();
        jmiNuevoAlumno = new javax.swing.JMenuItem();
        jmiModificarAlumno = new javax.swing.JMenuItem();
        jMenuConsulta = new javax.swing.JMenu();
        jmiConsultaAnimalP = new javax.swing.JMenuItem();
        jmiConsultaAnimalG = new javax.swing.JMenuItem();
        jMenuRetorno = new javax.swing.JMenu();
        jmiRetornoAnimalP = new javax.swing.JMenuItem();
        jmiRetornoAnimalPequenio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmDerivacionP = new javax.swing.JMenuItem();
        jMenuListaderivaciones = new javax.swing.JMenuItem();
        jMenuAnalisis = new javax.swing.JMenu();
        jMenuHemograma = new javax.swing.JMenuItem();
        jMenuQumica = new javax.swing.JMenuItem();
        jMenuUrianálisis = new javax.swing.JMenuItem();
        jMenuReportes = new javax.swing.JMenu();
        ReporteHemograma = new javax.swing.JMenuItem();
        ReporteQuimica = new javax.swing.JMenuItem();
        Urianálisis = new javax.swing.JMenuItem();
        MenuEstadistica = new javax.swing.JMenu();
        Consulta1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión Animales");
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jdpFondo.setPreferredSize(new java.awt.Dimension(1024, 768));

        jpLogo.setPreferredSize(new java.awt.Dimension(600, 300));

        javax.swing.GroupLayout jpLogoLayout = new javax.swing.GroupLayout(jpLogo);
        jpLogo.setLayout(jpLogoLayout);
        jpLogoLayout.setHorizontalGroup(
            jpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jpLogoLayout.setVerticalGroup(
            jpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jdpFondoLayout = new javax.swing.GroupLayout(jdpFondo);
        jdpFondo.setLayout(jdpFondoLayout);
        jdpFondoLayout.setHorizontalGroup(
            jdpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpFondoLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jpLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jdpFondoLayout.setVerticalGroup(
            jdpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpFondoLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jpLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jdpFondo.setLayer(jpLogo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuSistema.setText("Sistema");

        jmiSalir.setText("Salir ");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jMenuSistema.add(jmiSalir);

        jMenuBar1.add(jMenuSistema);

        jMenuDuenio.setText("Dueños");

        jmiNuevoDuenio.setText("Agregar nuevo dueño");
        jmiNuevoDuenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoDuenioActionPerformed(evt);
            }
        });
        jMenuDuenio.add(jmiNuevoDuenio);

        jmiEliminarDueño.setText("Eliminar Dueño");
        jmiEliminarDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEliminarDueñoActionPerformed(evt);
            }
        });
        jMenuDuenio.add(jmiEliminarDueño);

        jmiModificarDueño.setText("Modificar Dueño");
        jmiModificarDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiModificarDueñoActionPerformed(evt);
            }
        });
        jMenuDuenio.add(jmiModificarDueño);

        jMenuBar1.add(jMenuDuenio);

        jMenuAnimal.setText("Animales");

        jmiNuevoAnimalP.setText("Agregar nuevo animal pequeño");
        jmiNuevoAnimalP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoAnimalPActionPerformed(evt);
            }
        });
        jMenuAnimal.add(jmiNuevoAnimalP);

        jmiModificarAnimalP.setText("Modificar Animal Pequeño");
        jmiModificarAnimalP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiModificarAnimalPActionPerformed(evt);
            }
        });
        jMenuAnimal.add(jmiModificarAnimalP);

        jmiEliminarAnimalP.setText("Elimnar Animal Pequeño");
        jmiEliminarAnimalP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEliminarAnimalPActionPerformed(evt);
            }
        });
        jMenuAnimal.add(jmiEliminarAnimalP);

        jmiNuevoAnimalG.setText("Agregar Nuevo Animal Grande");
        jmiNuevoAnimalG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoAnimalGActionPerformed(evt);
            }
        });
        jMenuAnimal.add(jmiNuevoAnimalG);

        jmiModificarAnimalG.setText("Modifical Animal Grande");
        jmiModificarAnimalG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiModificarAnimalGActionPerformed(evt);
            }
        });
        jMenuAnimal.add(jmiModificarAnimalG);

        jmiNuevaRaza.setText("Especie y Raza Animal Pequeño");
        jmiNuevaRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevaRazaActionPerformed(evt);
            }
        });
        jMenuAnimal.add(jmiNuevaRaza);

        jMenuItem2.setText("Especie y Raza Animal Grande");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuAnimal.add(jMenuItem2);

        jMenuBar1.add(jMenuAnimal);

        jMenuDoctor.setText("Doctores");

        jmiNuevoDoctor.setText("Nuevo Doctor");
        jmiNuevoDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoDoctorActionPerformed(evt);
            }
        });
        jMenuDoctor.add(jmiNuevoDoctor);

        jmiModificarDoctor.setText("Modificar Doctor");
        jmiModificarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiModificarDoctorActionPerformed(evt);
            }
        });
        jMenuDoctor.add(jmiModificarDoctor);

        jMenuBar1.add(jMenuDoctor);

        jMenuAlumno.setText("Alumnos");

        jmiNuevoAlumno.setText("Nuevo Alumno");
        jmiNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoAlumnoActionPerformed(evt);
            }
        });
        jMenuAlumno.add(jmiNuevoAlumno);

        jmiModificarAlumno.setText("Modificar Alumno");
        jmiModificarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiModificarAlumnoActionPerformed(evt);
            }
        });
        jMenuAlumno.add(jmiModificarAlumno);

        jMenuBar1.add(jMenuAlumno);

        jMenuConsulta.setText("Consulta");

        jmiConsultaAnimalP.setText("Consulta Animal Pequeño");
        jmiConsultaAnimalP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaAnimalPActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jmiConsultaAnimalP);

        jmiConsultaAnimalG.setText("Consulta Animal Grande");
        jmiConsultaAnimalG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaAnimalGActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jmiConsultaAnimalG);

        jMenuBar1.add(jMenuConsulta);

        jMenuRetorno.setText("Retorno");

        jmiRetornoAnimalP.setText("Retorno Animales Pequeños");
        jmiRetornoAnimalP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRetornoAnimalPActionPerformed(evt);
            }
        });
        jMenuRetorno.add(jmiRetornoAnimalP);

        jmiRetornoAnimalPequenio.setText("Retorno Animales Grandes");
        jmiRetornoAnimalPequenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRetornoAnimalPequenioActionPerformed(evt);
            }
        });
        jMenuRetorno.add(jmiRetornoAnimalPequenio);

        jMenuBar1.add(jMenuRetorno);

        jMenu2.setText("Derivaciones");

        jmDerivacionP.setText("Nueva Derivación");
        jmDerivacionP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDerivacionPActionPerformed(evt);
            }
        });
        jMenu2.add(jmDerivacionP);

        jMenuListaderivaciones.setText("Lista de Derivaciones");
        jMenu2.add(jMenuListaderivaciones);

        jMenuBar1.add(jMenu2);

        jMenuAnalisis.setText("Análisis Clínicos");

        jMenuHemograma.setText("Hemograma");
        jMenuHemograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHemogramaActionPerformed(evt);
            }
        });
        jMenuAnalisis.add(jMenuHemograma);

        jMenuQumica.setText("Química Clinica");
        jMenuQumica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQumicaActionPerformed(evt);
            }
        });
        jMenuAnalisis.add(jMenuQumica);

        jMenuUrianálisis.setText("Urianálisis");
        jMenuUrianálisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUrianálisisActionPerformed(evt);
            }
        });
        jMenuAnalisis.add(jMenuUrianálisis);

        jMenuBar1.add(jMenuAnalisis);

        jMenuReportes.setText("Reportes");

        ReporteHemograma.setText("Hemogramas");
        ReporteHemograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteHemogramaActionPerformed(evt);
            }
        });
        jMenuReportes.add(ReporteHemograma);

        ReporteQuimica.setText("Química Clinica");
        ReporteQuimica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteQuimicaActionPerformed(evt);
            }
        });
        jMenuReportes.add(ReporteQuimica);

        Urianálisis.setText("Urianálisis");
        Urianálisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UrianálisisActionPerformed(evt);
            }
        });
        jMenuReportes.add(Urianálisis);

        jMenuBar1.add(jMenuReportes);

        MenuEstadistica.setText("Estadística");

        Consulta1.setText("Consulta de Docentes y Alumnos");
        Consulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consulta1ActionPerformed(evt);
            }
        });
        MenuEstadistica.add(Consulta1);

        jMenuBar1.add(MenuEstadistica);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNuevoDuenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoDuenioActionPerformed
        NuevoDueño duenio = new NuevoDueño();
        jdpFondo.add(duenio);
        duenio.show();
    }//GEN-LAST:event_jmiNuevoDuenioActionPerformed

    private void jmiEliminarDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEliminarDueñoActionPerformed
        // TODO add your handling code here:
        EliminarDueño duenio = new EliminarDueño();
        jdpFondo.add(duenio);
        duenio.show();
    }//GEN-LAST:event_jmiEliminarDueñoActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiModificarDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiModificarDueñoActionPerformed
        // TODO add your handling code here:
        ModificarDueño duenio = new ModificarDueño();
        jdpFondo.add(duenio);
        duenio.show();
    }//GEN-LAST:event_jmiModificarDueñoActionPerformed

    private void jmiNuevoAnimalPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoAnimalPActionPerformed
        // TODO add your handling code here:
        NuevoAnimalP duenio = new NuevoAnimalP();
        jdpFondo.add(duenio);
        duenio.show();
    }//GEN-LAST:event_jmiNuevoAnimalPActionPerformed

    private void jmiModificarAnimalPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiModificarAnimalPActionPerformed
        // TODO add your handling code here:
        ModificarAnimalP duenio = new ModificarAnimalP();
        jdpFondo.add(duenio);
        duenio.show();
    }//GEN-LAST:event_jmiModificarAnimalPActionPerformed

    private void jmiEliminarAnimalPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEliminarAnimalPActionPerformed
        // TODO add your handling code here:
        BuscarAnimalP animal = new BuscarAnimalP();
        jdpFondo.add(animal);
        animal.show();
    }//GEN-LAST:event_jmiEliminarAnimalPActionPerformed

    private void jmiNuevoAnimalGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoAnimalGActionPerformed
        // TODO add your handling code here:
        NuevoAnimalG animal = new NuevoAnimalG();
        jdpFondo.add(animal);
        animal.show();
    }//GEN-LAST:event_jmiNuevoAnimalGActionPerformed

    private void jmiModificarAnimalGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiModificarAnimalGActionPerformed
        // TODO add your handling code here:
        ModificarAnimalG animal = new ModificarAnimalG();
        jdpFondo.add(animal);
        animal.show();
    }//GEN-LAST:event_jmiModificarAnimalGActionPerformed

    private void jmiNuevoDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoDoctorActionPerformed
        // TODO add your handling code here:
        NuevoDoctor doctor = new NuevoDoctor();
        jdpFondo.add(doctor);
        doctor.show();
    }//GEN-LAST:event_jmiNuevoDoctorActionPerformed

    private void jmiModificarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiModificarDoctorActionPerformed
        // TODO add your handling code here:
        ModificarDoctor doctor = new ModificarDoctor();
        jdpFondo.add(doctor);
        doctor.show();
    }//GEN-LAST:event_jmiModificarDoctorActionPerformed

    private void jmiNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoAlumnoActionPerformed
        // TODO add your handling code here:
        NuevoAlumno alumno = new NuevoAlumno();
        jdpFondo.add(alumno);
        alumno.show();
    }//GEN-LAST:event_jmiNuevoAlumnoActionPerformed

    private void jmiModificarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiModificarAlumnoActionPerformed
        // TODO add your handling code here:
        ModificarAlumno alumno = new ModificarAlumno();
        jdpFondo.add(alumno);
        alumno.show();
    }//GEN-LAST:event_jmiModificarAlumnoActionPerformed

    private void jmiNuevaRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevaRazaActionPerformed
        // TODO add your handling code here:
        EspecieRazaAnimalP raza = new EspecieRazaAnimalP();
        jdpFondo.add (raza);
        raza.show();
    }//GEN-LAST:event_jmiNuevaRazaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        EspecieRazaAnimalG raza = new EspecieRazaAnimalG();
        jdpFondo.add (raza);
        raza.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmiConsultaAnimalPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaAnimalPActionPerformed
        // TODO add your handling code here:
        ConsultaAnimalP raza = new ConsultaAnimalP();
        jdpFondo.add (raza);
        raza.show();
    }//GEN-LAST:event_jmiConsultaAnimalPActionPerformed

    private void jmiConsultaAnimalGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaAnimalGActionPerformed
        // TODO add your handling code here:
        ConsultaAnimalG consulta = new ConsultaAnimalG();
        jdpFondo.add(consulta);
        consulta.show(); 
    }//GEN-LAST:event_jmiConsultaAnimalGActionPerformed

    private void jmiRetornoAnimalPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRetornoAnimalPActionPerformed
        // TODO add your handling code here:
        BuscarCasoClinico buscar = new BuscarCasoClinico();
        jdpFondo.add(buscar);
        buscar.show();
        
    }//GEN-LAST:event_jmiRetornoAnimalPActionPerformed

    private void jmiRetornoAnimalPequenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRetornoAnimalPequenioActionPerformed
        // TODO add your handling code here:
        BuscarCasoClinicoG buscar = new BuscarCasoClinicoG();
        jdpFondo.add(buscar);
        buscar.show();
    }//GEN-LAST:event_jmiRetornoAnimalPequenioActionPerformed

    private void jMenuHemogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHemogramaActionPerformed
        // TODO add your handling code here:
        Hemograma analisis = new Hemograma();
        jdpFondo.add (analisis);
        analisis.show();
    }//GEN-LAST:event_jMenuHemogramaActionPerformed

    private void jMenuQumicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQumicaActionPerformed
        // TODO add your handling code here:
        QuimicaClinica analisis = new QuimicaClinica();
        jdpFondo.add (analisis);
        analisis.show();
    }//GEN-LAST:event_jMenuQumicaActionPerformed

    private void jMenuUrianálisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUrianálisisActionPerformed
        // TODO add your handling code here:
        Urianalisis analisis = new Urianalisis();
        jdpFondo.add (analisis);
        analisis.show();
    }//GEN-LAST:event_jMenuUrianálisisActionPerformed

    private void ReporteHemogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteHemogramaActionPerformed
        // TODO add your handling code here:
          BuscarHemograma reporte = new BuscarHemograma();
        jdpFondo.add (reporte);
        reporte.show();
    }//GEN-LAST:event_ReporteHemogramaActionPerformed

    private void ReporteQuimicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteQuimicaActionPerformed
        // TODO add your handling code here:
        BuscarQuimicaClinica reporte = new BuscarQuimicaClinica();
        jdpFondo.add (reporte);
        reporte.show();
    }//GEN-LAST:event_ReporteQuimicaActionPerformed

    private void UrianálisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrianálisisActionPerformed
        // TODO add your handling code here:
        BuscarUrianalisis reporte = new BuscarUrianalisis();
        jdpFondo.add (reporte);
        reporte.show();
    }//GEN-LAST:event_UrianálisisActionPerformed

    private void Consulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consulta1ActionPerformed
        // TODO add your handling code here:
            EstadisticaAnalisisDocenteAlumno reporte = new EstadisticaAnalisisDocenteAlumno();
        jdpFondo.add (reporte);
        reporte.show();
    }//GEN-LAST:event_Consulta1ActionPerformed

    private void jmDerivacionPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDerivacionPActionPerformed
        // TODO add your handling code here:
        DerivacionP derivacion = new DerivacionP ();
        jdpFondo.add (derivacion);
        derivacion.show();
    }//GEN-LAST:event_jmDerivacionPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new PantallaPrincipal().setVisible(true);
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Consulta1;
    private javax.swing.JMenu MenuEstadistica;
    private javax.swing.JMenuItem ReporteHemograma;
    private javax.swing.JMenuItem ReporteQuimica;
    private javax.swing.JMenuItem Urianálisis;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuAlumno;
    private javax.swing.JMenu jMenuAnalisis;
    private javax.swing.JMenu jMenuAnimal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsulta;
    private javax.swing.JMenu jMenuDoctor;
    private javax.swing.JMenu jMenuDuenio;
    private javax.swing.JMenuItem jMenuHemograma;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuListaderivaciones;
    private javax.swing.JMenuItem jMenuQumica;
    private javax.swing.JMenu jMenuReportes;
    private javax.swing.JMenu jMenuRetorno;
    private javax.swing.JMenu jMenuSistema;
    private javax.swing.JMenuItem jMenuUrianálisis;
    public static javax.swing.JDesktopPane jdpFondo;
    private javax.swing.JMenuItem jmDerivacionP;
    private javax.swing.JMenuItem jmiConsultaAnimalG;
    private javax.swing.JMenuItem jmiConsultaAnimalP;
    private javax.swing.JMenuItem jmiEliminarAnimalP;
    private javax.swing.JMenuItem jmiEliminarDueño;
    private javax.swing.JMenuItem jmiModificarAlumno;
    private javax.swing.JMenuItem jmiModificarAnimalG;
    private javax.swing.JMenuItem jmiModificarAnimalP;
    private javax.swing.JMenuItem jmiModificarDoctor;
    private javax.swing.JMenuItem jmiModificarDueño;
    private javax.swing.JMenuItem jmiNuevaRaza;
    private javax.swing.JMenuItem jmiNuevoAlumno;
    private javax.swing.JMenuItem jmiNuevoAnimalG;
    private javax.swing.JMenuItem jmiNuevoAnimalP;
    private javax.swing.JMenuItem jmiNuevoDoctor;
    private javax.swing.JMenuItem jmiNuevoDuenio;
    private javax.swing.JMenuItem jmiRetornoAnimalP;
    private javax.swing.JMenuItem jmiRetornoAnimalPequenio;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JPanel jpLogo;
    // End of variables declaration//GEN-END:variables
}
