/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ModuloDueño;

import Clases.MySQL;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ale
 */
public class DetalleDueño extends javax.swing.JInternalFrame {

    /**
     * Creates new form ABMcliente
     */
    public DetalleDueño() {
        initComponents();
        cargarTabla();
        
        jlapellido.setText(jtDueño.getValueAt(0, 0).toString());
        jlnombre.setText(jtDueño.getValueAt(0, 1).toString());
        jldni.setText(jtDueño.getValueAt(0, 2).toString());
        jlemail.setText(jtDueño.getValueAt(0, 3).toString());
        jlfacebook.setText(jtDueño.getValueAt(0, 4).toString());
        jldomicilio.setText(jtDueño.getValueAt(0, 5).toString());
        jlciudad.setText(jtDueño.getValueAt(0, 6).toString());
        jlcelular.setText(jtDueño.getValueAt(0, 7).toString());
        jlfijo.setText(jtDueño.getValueAt(0, 8).toString());
        
        jtDueño.setVisible(false);
        
              
       
        
       
    }
    
    public void cargarTabla(){
        int fila = EliminarDueño.jtDuenio.getSelectedRow();
        String dni= EliminarDueño.jtDuenio.getValueAt(fila, 2).toString();
        String[] columNames = {"Apellido","Nombre","DNI","E-Mail","Facebook","Domicilio","Ciudad","Celular","Tel.Fijo"};          
        String colName[] = {"apellido","nombre","dni_duenio","email","facebook","domicilio","ciudad","telefono_celular","telefono_fijo"};        
        //nombre de columnas, tabla, instruccion sql
        dtDuenio = duenio.GetTabla(colName, "duenio", "SELECT * FROM `duenio` WHERE `dni_duenio`="+dni+" ");
        // se colocan los datos en la tabla
        DefaultTableModel datos = new DefaultTableModel(dtDuenio,columNames);                        
        jtDueño.setModel(datos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content f this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_duenio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlnombre = new javax.swing.JLabel();
        jlapellido = new javax.swing.JLabel();
        jldni = new javax.swing.JLabel();
        jlciudad = new javax.swing.JLabel();
        jldomicilio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDueño = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlfacebook = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlemail = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlcelular = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlfijo = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("DETALLE DEL DUEÑO");

        jp_duenio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL DUEÑO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jp_duenio.setToolTipText("");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel5.setText("Domicilio:");

        jLabel6.setText("Ciudad:");

        jLabel8.setText("Dni:");

        jlnombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlnombre.setText("nombre");

        jlapellido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlapellido.setText("apellido");

        jldni.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jldni.setText("dni");

        jlciudad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlciudad.setText("ciudad");

        jldomicilio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jldomicilio.setText("domicilio");

        javax.swing.GroupLayout jp_duenioLayout = new javax.swing.GroupLayout(jp_duenio);
        jp_duenio.setLayout(jp_duenioLayout);
        jp_duenioLayout.setHorizontalGroup(
            jp_duenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_duenioLayout.createSequentialGroup()
                .addGroup(jp_duenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_duenioLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jp_duenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_duenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlapellido)
                            .addComponent(jlnombre)))
                    .addGroup(jp_duenioLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jp_duenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_duenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jldomicilio)
                            .addComponent(jlciudad)
                            .addComponent(jldni))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_duenioLayout.setVerticalGroup(
            jp_duenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_duenioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_duenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlnombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_duenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlapellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_duenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jldni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_duenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlciudad)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_duenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jldomicilio)
                    .addComponent(jLabel5)))
        );

        jtDueño.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtDueño);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTACTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel4.setText("Facebook:");

        jlfacebook.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlfacebook.setText("facebook");

        jLabel3.setText("E-mail:");

        jlemail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlemail.setText("email");

        jLabel7.setText("Celular:");

        jlcelular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlcelular.setText("celular");

        jLabel10.setText("Teléfono Fijo:");

        jlfijo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlfijo.setText("fijo");

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlfijo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlfacebook)
                            .addComponent(jlemail)
                            .addComponent(jlcelular)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlfacebook))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlemail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlcelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jlfijo))
                .addGap(18, 18, 18)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_duenio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jp_duenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jp_duenio.getAccessibleContext().setAccessibleName("Datos del Dueño");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed
    MySQL duenio = new MySQL();
    Object[][] dtDuenio; 
    int fila = -1;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JLabel jlapellido;
    private javax.swing.JLabel jlcelular;
    private javax.swing.JLabel jlciudad;
    private javax.swing.JLabel jldni;
    private javax.swing.JLabel jldomicilio;
    private javax.swing.JLabel jlemail;
    private javax.swing.JLabel jlfacebook;
    private javax.swing.JLabel jlfijo;
    private javax.swing.JLabel jlnombre;
    private javax.swing.JPanel jp_duenio;
    private javax.swing.JTable jtDueño;
    // End of variables declaration//GEN-END:variables
}
