/* * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ModuloAnimal;

import Clases.MySQL;
import Clases.PantallaPrincipal;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;





/**
 *
 * @author Ale
 */
public class NuevoAnimalG extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevoAnimalP
     */
    public NuevoAnimalG() {
        initComponents();
        
        ImgAnimalp img = new ImgAnimalp();
        jpimagen.add(img);
        jpimagen.repaint();
        cargarEspecies();
        cargarRazas();
      
 
      }
    
    private void cargarEspecies(){
       
        //nombre de columnas, tabla, instruccion sql
        dcEspecie = animal.GetColumna("lista_especieg", "especie", "SELECT * FROM `lista_especieg");
        // se colocan los datos en la tabla
        DefaultComboBoxModel datos = new DefaultComboBoxModel(dcEspecie);
        jcbEspecie.setModel(datos);
    }
    private void cargarRazas(){
        
      jcbRaza.removeAllItems();
        String especie = jcbEspecie.getSelectedItem().toString();
       
        String cod_especie = animal.GetData("cod_especie", "SELECT cod_especie FROM lista_especieg WHERE especie = \""+especie+"\"");
        
//nombre de columnas, tabla, instruccion sql
        dcRaza = animal.GetColumna("lista_razag", "raza", "SELECT * FROM lista_razag WHERE cod_especie =\""+cod_especie+"\"");
        
        // se colocan los datos en la tabla
        DefaultComboBoxModel datos = new DefaultComboBoxModel(dcRaza);
        jcbRaza.setModel(datos);
        int a = jcbRaza.getItemCount();
        //depurador de jcbRaza de item null
        int i=0;
        a--;
        while(a>=i){
            if(jcbRaza.getItemAt(i)==null){
                jcbRaza.removeItemAt(i);
                a--;
                i--;
            }
            i++;
        }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDueño = new javax.swing.JPanel();
        jbBuscarDueño = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlDni = new javax.swing.JLabel();
        jpAnimal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtnombre = new javax.swing.JTextField();
        jcbEspecie = new javax.swing.JComboBox();
        jbNuevaEspecie = new javax.swing.JButton();
        jcbRaza = new javax.swing.JComboBox();
        jbNuevaRaza = new javax.swing.JButton();
        jcbSexo = new javax.swing.JComboBox();
        jtfPeso = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jtfColor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jpimagen = new javax.swing.JPanel();
        jbAgregar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("AGREGAR NUEVO ANIMAL GRANDES");

        jpDueño.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL DUEÑO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jbBuscarDueño.setText("Buscar Dueño");
        jbBuscarDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarDueñoActionPerformed(evt);
            }
        });

        jLabel1.setText("Apellido:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("DNI:");

        jlApellido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlApellido.setText("apellido");

        jlNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlNombre.setText("nombre");

        jlDni.setText("dni");

        javax.swing.GroupLayout jpDueñoLayout = new javax.swing.GroupLayout(jpDueño);
        jpDueño.setLayout(jpDueñoLayout);
        jpDueñoLayout.setHorizontalGroup(
            jpDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDueñoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jpDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(jpDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDueñoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jlApellido))
                    .addGroup(jpDueñoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jpDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlDni)
                            .addComponent(jlNombre)
                            .addComponent(jbBuscarDueño, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDueñoLayout.setVerticalGroup(
            jpDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDueñoLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jpDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlApellido))
                .addGap(18, 18, 18)
                .addGroup(jpDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlNombre))
                .addGap(18, 18, 18)
                .addGroup(jpDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDni)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jbBuscarDueño, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jpAnimal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL ANIMAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel4.setText("Nombre:");

        jLabel5.setText("Especie:");

        jLabel6.setText("Raza:");

        jLabel7.setText("Sexo:");

        jLabel8.setText("Fecha de Nacimiento:");

        jLabel9.setText("Peso:");

        jcbEspecie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbEspecieItemStateChanged(evt);
            }
        });
        jcbEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEspecieActionPerformed(evt);
            }
        });

        jbNuevaEspecie.setText("Agregar Especie");
        jbNuevaEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevaEspecieActionPerformed(evt);
            }
        });

        jbNuevaRaza.setText("Agregar Raza");
        jbNuevaRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevaRazaActionPerformed(evt);
            }
        });

        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Macho", "Hembra" }));

        jLabel10.setText("Color");

        javax.swing.GroupLayout jpAnimalLayout = new javax.swing.GroupLayout(jpAnimal);
        jpAnimal.setLayout(jpAnimalLayout);
        jpAnimalLayout.setHorizontalGroup(
            jpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(jpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpAnimalLayout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(jLabel9))
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(jpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jpAnimalLayout.createSequentialGroup()
                            .addComponent(jcbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbNuevaEspecie))
                        .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpAnimalLayout.createSequentialGroup()
                            .addComponent(jcbRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbNuevaRaza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jtfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtfColor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAnimalLayout.setVerticalGroup(
            jpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAnimalLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAnimalLayout.createSequentialGroup()
                        .addGroup(jpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jcbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcbRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbNuevaRaza))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbNuevaEspecie))
                .addGap(9, 9, 9)
                .addGroup(jpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpimagen.setPreferredSize(new java.awt.Dimension(128, 128));

        javax.swing.GroupLayout jpimagenLayout = new javax.swing.GroupLayout(jpimagen);
        jpimagen.setLayout(jpimagenLayout);
        jpimagenLayout.setHorizontalGroup(
            jpimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        jpimagenLayout.setVerticalGroup(
            jpimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpimagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpimagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpDueño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarDueñoActionPerformed
        // TODO add your handling code here:
        ListaDueñoG lista = new ListaDueñoG();
        PantallaPrincipal.jdpFondo.add(lista);
        lista.toFront();
        lista.setVisible(true);
        ListaDueñoG.jLabel1.setText("1");
        
    }//GEN-LAST:event_jbBuscarDueñoActionPerformed

    private void jcbEspecieItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbEspecieItemStateChanged
        // TODO add your handling code here:
      cargarRazas();
        
    }//GEN-LAST:event_jcbEspecieItemStateChanged

    private void jbNuevaEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevaEspecieActionPerformed
        // TODO add your handling code here:
        String nuevaesp = JOptionPane.showInputDialog(rootPane,"Ingrese la especie que desea agregar:","Nueva Especie", WIDTH);
        boolean aux = animal.existe("lista_especieg", "especie", nuevaesp);
        if (aux==true){
            JOptionPane.showMessageDialog(rootPane, "El registro ya existe");
        }else{
        String datos[] = {nuevaesp};   
        //array de datos , instruccion sql
        animal.InsertarRegistro(datos, "insert into lista_especieg (`especie`)values(?)");
        cargarEspecies();
        //buscamos el cod_especie correspondiente
        int ultimo= jcbEspecie.getItemCount()-1;
        String especie = jcbEspecie.getItemAt(ultimo).toString();
        String cod_especie = animal.GetData("cod_especie", "SELECT cod_especie FROM lista_especieg WHERE especie = \""+especie+"\"");
        
//agregamos la nueva raza
        String nuevaraza = JOptionPane.showInputDialog(rootPane,"Ingrese una raza inicial para "+nuevaesp+"","Nueva Raza",WIDTH);
        String dato[]= {cod_especie,nuevaraza};
        animal.InsertarRegistro(dato, "insert into lista_razag (`cod_especie`,`raza`)values(?,?)");
        cargarRazas();
        
        }
        
       
        
        
    }//GEN-LAST:event_jbNuevaEspecieActionPerformed

    private void jcbEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEspecieActionPerformed

    private void jbNuevaRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevaRazaActionPerformed
        // TODO add your handling code here:
        String especie= (String)jcbEspecie.getSelectedItem();
        String cod_especie = animal.GetData("cod_especie", "SELECT cod_especie FROM lista_especieg WHERE especie = \""+especie+"\"");
        String nuevaraza = JOptionPane.showInputDialog(rootPane,"Ingrese una raza para "+especie+"","Nueva Raza",WIDTH);
        boolean aux = animal.existe("lista_razag", "raza", nuevaraza);
            if (aux==true){
            JOptionPane.showMessageDialog(rootPane, "El registro ya existe");
            }else{
            String dato[]= {cod_especie,nuevaraza};
            animal.InsertarRegistro(dato, "insert into lista_razag (`cod_especie`,`raza`)values(?,?)");
            cargarRazas();      
                        }
    }//GEN-LAST:event_jbNuevaRazaActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // TODO add your handling code here:
        String nombre = jtnombre.getText();
        String especie= (String)jcbEspecie.getSelectedItem();
        //int cod_especie = Integer.parseInt(animal.GetData("cod_especie", "SELECT cod_especie FROM lista_especie WHERE especie = \""+especie+"\""));
        String cod_especie =animal.GetData("cod_especie", "SELECT cod_especie FROM lista_especieg WHERE especie = \""+especie+"\"");
        String raza = (String)jcbRaza.getSelectedItem();
        //int cod_raza = Integer.parseInt(animal.GetData("cod_raza", "SELECT cod_raza FROM lista_raza WHERE raza = \""+raza+"\""));
        String cod_raza = animal.GetData("cod_raza", "SELECT cod_raza FROM lista_razag WHERE raza = \""+raza+"\"");
        //int peso = Integer.parseInt(jtfPeso.getText());
        String peso = jtfPeso.getText();
        //Date nacio = jDateChooser1.getDate();
	DateFormat fecha = new SimpleDateFormat("yyyy-MM-dd");
        Date nacio = jDateChooser1.getDate();        
        String date = fecha.format(nacio); 
        String sexo = (String)jcbSexo.getSelectedItem();
        String color= jtfColor.getText();
        //int dni = Integer.parseInt(jlDni.getText());
        String dni = jlDni.getText();
        String life ="si";
        boolean aux = animal.existe("animal_grandes", "nombre", nombre);
        if (aux==true){
            JOptionPane.showMessageDialog(rootPane, "El registro ya existe");
        }else{
              String datos[] = {nombre,cod_especie,cod_raza,peso,date,sexo,color,dni,life};   
        //array de datos , instruccion sql
        animal.InsertarRegistro(datos, "insert into `animal_grandes`( `nombre`, `cod_especie`, `cod_raza`, `peso`, `nacimiento`, `sexo`, `color`, `dni_duenio`, `vivo`)values(?,?,?,?,?,?,?,?,?)");
        
        }
    }//GEN-LAST:event_jbAgregarActionPerformed

    MySQL animal = new MySQL(); 
    Object[] dcEspecie;
    Object[] dcRaza;
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAgregar;
    public static javax.swing.JButton jbBuscarDueño;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbNuevaEspecie;
    private javax.swing.JButton jbNuevaRaza;
    private javax.swing.JComboBox jcbEspecie;
    private javax.swing.JComboBox jcbRaza;
    private javax.swing.JComboBox jcbSexo;
    public static javax.swing.JLabel jlApellido;
    public static javax.swing.JLabel jlDni;
    public static javax.swing.JLabel jlNombre;
    private javax.swing.JPanel jpAnimal;
    private javax.swing.JPanel jpDueño;
    private javax.swing.JPanel jpimagen;
    private javax.swing.JTextField jtfColor;
    private javax.swing.JTextField jtfPeso;
    private javax.swing.JTextField jtnombre;
    // End of variables declaration//GEN-END:variables
}
